[[intro]]
== Introduction

The RISC-V ISA and its standardized extensions provide a rich set of
instructions suitable for a wide range of applications, starting from
specialized microcontrollers to HPC systems.
The suitability for such a range of systems comes from the fact that
the RISC-V ISA is modularized with a base instruction set and a range
of extensions that target specific target applications and functionality.

The T-Head extension collection follows the principles of the RISC-V ISA.
The collection consists of the following ISA extensions:

* `XTheadCmo` provides instructions for cache management.
* `XTheadSync` provides instructions for multi-processor synchronization.
* `XTheadBa` provides instructions for address calculations.
* `XTheadBb` provides instructions for basic bit-manipulation.
* `XTheadBs` provides single-bit instructions.
* `XTheadCondMov` provides instructions for conditional moves.
* `XTheadMemIdx` provides GPR memory operations.
* `XTheadMemPair` provides two-GP-register memory operations.
* `XTheadFMemIdx` provides floating-point memory operations.
* `XTheadMac` provides multiply-accumulate instructions.

All T-Head extensions are defined for RV32 and RV64.

[NOTE]
====
The name RISC-V indexterm:[RISC-V] was chosen to represent the fifth major RISC ISA design from UC Berkeley (RISC-I cite:[riscI-isca1981], RISC-II cite:[Katevenis:1983], SOAR cite:[Ungar:1984], and SPUR cite:[spur-jsscc1989] were the first four). We also pun on the use of the Roman numeral "V" to signify "variations" and "vectors", as support for a range of architecture research, including various data-parallel accelerators, is an explicit goal of the ISA design.
====

