[#xtheadee]
== T-Head extension enablement (XTheadEE)

The `XTheadEE` ISA extension defines a M-mode status register,
that provides a bit to enable all implemented T-Head extensions.
The `XTheadEE` ISA extension, if implemented, is always enabled.

The table below gives an overview of the CSRs:

[cols="^3,^3,12,18",stripes=even,options="header"]
|===
| Address | Name | CSR
| 0x7C0   | `th.mxstatus` | <<#xtheadee-csrs-mxstatus>>
|===

[#xtheadee-csrs,reftext="CSRs"]
=== CSRs

[#csrs-xtheadee-mxstatus,reftext=T-Head extension status register]
==== th.mxstatus

Description::
The `th.mxstatus` register has 64 bits and provides the enable bit for other T-Head specific extensions.

Bit assignment::
[wavedrom, , svg]
....
{reg:[
    { bits:  22, name: 'reserved' },
    { bits:  1, name: 0x0, attr: ['theadisaee'] },
    { bits:  9, name: 'reserved' },
    { bits:  32, name: 'reserved' },
], config: { lanes:2 }
}
....

Field description::

`theadisaee` defines the enablement status of T-Head ISA extensions.
When `theadisaee` is `0`, all T-Head ISA extensions (except XTheadEE)
are disabled and executing a corresponding instruction will cause an
illegal instruction exception.
When `theadisaee` is `1`, all T-Head ISA extensions are enabled and
the corresponding instructions operate as documented.

Permission::
The `mxstatus` register is readable and writable in `M`-mode. Access in other modes will trigger an illegal instruction exception.

Availability::
The `th.mxstatus` CSR is always available if the `XTheadEE` ISA extension is implemented.

Included in::
[%header]
|===
|Extension

|XTheadEE (<<#xtheadee>>)
|===
