[#insns-xtheadcmo-dcache_cipa,reftext=Clean & invalidate D-cache at PA]
==== th.dcache.cipa

Synopsis::
Clean and invalidate D-cache at PA

Mnemonic::
th.dcache.cipa _rs1_

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 0x0 },
    { bits:  3, name: 0x0, attr: ['CMO'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 0xB, attr: ['dcache.cipa'] },
    { bits:  7, name: 0x01 },
]}
....

Description::
This instruction cleans and invalidates the cache lines that match the specified physical address in the D-cache.
If a cache line is dirty it will be written back to the next-level storage.

Operation::
[source,sail]
--
if (priv_level == U)
{
  <raise illegal instruction exception>
}

<write back all dirty data cache lines matching the PA>
<invalidate all data cache lines matching the PA>
--

Permission::
This instruction can be executed in all privilege levels higher than `U` mode.
Attempts to execute this instruction in `U` mode raise an illegal instruction exception.

Exceptions::
This instruction does not trigger any exceptions.

Included in::
[%header,cols="4,2"]
|===
|Extension
|HW requirements

|XTheadCmo (<<#xtheadcmo>>)
|D-cache
|===

