[#insns-xtheadcmo-dcache_cpa,reftext=Clean D-cache at PA]
==== th.dcache.cpa

Synopsis::
Clean D-cache at PA

an instruction that clears dirty page table entries that match
the specified physical addresses from the D-Cache

Mnemonic::
th.dcache.cpa _rs1_

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 0x0 },
    { bits:  3, name: 0x0, attr: ['CMO'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 0x9, attr: ['dcache.cpa'] },
    { bits:  7, name: 0x01 },
]}
....

Description::
This instruction cleans the cache lines that match the specified physical address in the D-cache.
If a cache line is dirty it will be written back to the next-level storage.

Operation::
[source,sail]
--
// illegal instruction exceptions
if (mxstatus.theadisaee != 1 ||
    ((priv_mode != M) && (priv_mode != S))
{
  <raise illegal instruction exception>
}
// execute instruction
<write back all dirty data cache lines matching the PA>
--

Permission::
This instruction can only be executed in `M` mode and `S` mode. Other modes will trigger an illegal instruction exception.

Exceptions::
This instruction does not trigger any exceptions.

Availability::
The instruction is only available if `mxstatus.theadisaee` is set to `1`. Otherwise this instruction will trigger an illegal instruction exception.

Included in::
[%header,cols="4,2"]
|===
|Extension
|HW requirements

|XTheadCmo (<<#xtheadcmo>>)
|D-cache
|===

