[#xtheadbb-insns-extu,reftext=Extract and zero-extend bits]
==== th.extu

Synopsis::
Extract and zero-extend bits.

Mnemonic::
th.extu _rd_, _rs1_, _imm1_, _imm2_

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x3, attr: ['Arithmetic'] },
    { bits:  5, name: 'rs1' },
    { bits:  6, name: 'imm2' },
    { bits:  6, name: 'imm1' },
]}
....

Description::
This operation extract the bits _imm1_.._imm2_ from register _rs1_, zero-extends the value, and stores the result in _rd_.

Operation::
[source,sail]
--
// illegal instruction exceptions
if (mxstatus.theadisaee != 1)
{
  <raise illegal instruction exception>
}

// execute instruction
reg[rd] := zero_extend(reg[rs1][imm1:imm2])
--

Permission::
This instruction is available in `M` mode, `S` mode, and `U` mode.

Exceptions::
This instruction does not trigger any exceptions.

Availability::
The instruction is only available if `mxstatus.theadisaee` is set to `1`.
Otherwise this instruction will trigger an illegal instruction exception.

Included in::
[%header]
|===
|Extension

|XTheadBb (<<#xtheadbb>>)
|===
