[#xtheadbb-insns-revw,reftext=Reverse byte order of word operand]
==== th.revw

Synopsis::
Reverse the byte order of a word operand.

Mnemonic::
th.revw _rd_, _rs1_

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['Arithmetic'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 0x0 },
    { bits:  2, name: 0x0 },
    { bits:  5, name: 0x12 },
]}
....

Description::
This operation reverses the byte order of the 32-bit value in _rs1_ and stores the result in _rd_.

Operation::
[source,sail]
--
// illegal instruction exceptions
if (mxstatus.theadisaee != 1)
{
  <raise illegal instruction exception>
}

// execute instruction
for i=0..3:
  j := 3 - i
  tmp[i] := reg[rs1][j]
reg[rd] := tmp
--

Permission::
This instruction is available in `M` mode, `S` mode, and `U` mode.

Exceptions::
This instruction does not trigger any exceptions.

Availability::
The instruction is only available if `mxstatus.theadisaee` is set to `1`.
Otherwise this instruction will trigger an illegal instruction exception.

Included in::
[%header]
|===
|Extension

|XTheadBb (<<#xtheadbb>>)
|===
