[#xtheadfmemidx-insns-flurw,reftext=Load unsigned indexed float]
==== th.flurw

Synopsis::
Load unsigned indexed single-precision floating point value.

Mnemonic::
th.flurw _rd_, _rs1_, _rs2_, _imm2_

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x6, attr: ['FMem-Load'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  2, name: 'imm2' },
    { bits:  5, name: 0x0a },
]}
....

Description::
This instruction loads a single-precision floating point value into FP register _rd_ from the address _rs1_ + (zero_extend(_rs2_) << _imm2_).

If the `D` extension is available the value will be one-extended.

Note, that this instruction is equivalent to a `zext.w _rs2_, _rs2_` followed by a `th.flrw` with the same arguments.

Operation::
[source,sail]
--
// illegal instruction exceptions
if (mxstatus.theadisaee != 1 ||
    have_extension("F"))
{
  <raise illegal instruction exception>
}

// execute instruction
addr := rs1 + (zero_extend(rs2) << imm2)
rd := one_extend(fmem[addr+3:addr])
--

Permission::
This instruction is available in `M` mode, `S` mode, and `U` mode.

Exceptions::
This instruction triggers the same exceptions that a corresponding `FLW` instructions would trigger.

Availability::
The instruction is only available if `mxstatus.theadisaee` is set to `1`.
and if the `F` extension is implemented.
Otherwise this instruction will trigger an illegal instruction exception.

Included in::
[%header]
|===
|Extension

|XTheadFMemIdx (<<#xtheadfmemidx>>)
|===

