[#xtheadfmemidx-insns-fsurd,reftext=Store unsigned indexed double]
==== th.fsurd

Synopsis::
Store unsigned indexed double-precision floating point value.

Mnemonic::
th.fsurd _rd_, _rs1_, _rs2_, _imm2_

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x7, attr: ['FMem-Store'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  2, name: 'imm2' },
    { bits:  5, name: 0x0e },
]}
....

Description::
This instruction stores a double-precision floating point value from FP register _rd_ to the address _rs1_ + (zero_extend(_rs2_) << _imm2_).

Note, that this instruction is equivalent to a `zext.w _rs2_, _rs2_` followed by a `th.fsrd` with the same arguments.

Operation::
[source,sail]
--
// illegal instruction exceptions
if (mxstatus.theadisaee != 1 ||
    have_extension("D"))
{
  <raise illegal instruction exception>
}

// execute instruction
addr := rs1 + (zero_extend(rs2) << imm2)
fmem[addr+7:addr] := rd
--

Permission::
This instruction is available in `M` mode, `S` mode, and `U` mode.

Exceptions::
This instruction triggers the same exceptions that two corresponding `FSD` instructions would trigger.

Availability::
The instruction is only available if `mxstatus.theadisaee` is set to `1`
and if the `D` extension is implemented.
Otherwise this instruction will trigger an illegal instruction exception.

Included in::
[%header]
|===
|Extension

|XTheadFMemIdx (<<#xtheadfmemidx>>)
|===

