[#xtheadmempair-insns-lwud,reftext=Load two unsigned 32-bit values]
==== th.lwud

Synopsis::
Load two unsigned 32-bit values from memory into two GPRs.

Mnemonic::
th.lwud _rd1_, _rd2_, (_rs1_), _imm2_, 3

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 'rd1' },
    { bits:  3, name: 0x4, attr: ['Mem-Load'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rd2' },
    { bits:  2, name: 'imm2' },
    { bits:  5, name: 0x1e },
]}
....

Description::
This instruction loads two unsigned 32-bit values into the two GP registers _rd1_ and _rd2_
from the address _rs1_ + (zero_extend(_imm2_) << 3).

Operation::
[source,sail]
--
// illegal instruction exceptions
if (mxstatus.theadisaee != 1)
{
  <raise illegal instruction exception>
}

// execute instruction
addr := rs1 + (zero_extend(imm2) << 3)
reg[rd1] := zero_extend(mem[addr+3:addr])
reg[rd2] := zero_extend(mem[addr+7:addr+3])
--

Permission::
This instruction is available in `M` mode, `S` mode, and `U` mode.

Exceptions::
This instruction triggers the same exceptions that two corresponding `LWU` instructions would trigger.

Availability::
The instruction is only available if `mxstatus.theadisaee` is set to `1`.
Otherwise this instruction will trigger an illegal instruction exception.

Included in::
[%header]
|===
|Extension

|XTheadMemPair (<<#xtheadmempair>>)
|===

