[#xtheadsync-insns-sfence_vmas,reftext=Invalidate TLB on all harts]
==== th.sfence.vmas

Synopsis::
Invalidate TLB (page table cache) on all harts via broadcasting.

Mnemonic::
th.sfence.vmas _rs1_, _rs2_

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 0x0 },
    { bits:  3, name: 0x0, attr: ['CMO'] },
    { bits:  5, name: 'rs1', attr: ['VA'] },
    { bits:  5, name: 'rs2', attr: ['ASID'] },
    { bits:  7, name: 0x02 },
]}
....

Description::
This instruction invalidates the TLB (page table cache) on all harts via broadcasting.
The register _rs1_ holds the virtual address (VA) and _rs2_ holds the address space identifier (ASID)
of the TLB entry that will be invalidated on all harts via broadcasting.

An operand that is zero is interpreted as match-all.
E.g. if _rs2_ is zero, then all TLB entries that match the VA in _rs1_ are invalidated on all harts via broadcasting.
Consequently, if both operands, _rs1_ and _rs2_, are zero, then all TLB entries are invalidated on all harts via broadcasting.

Operation::
[source,sail]
--
if (priv_level == U)
{
  <raise illegal instruction exception>
}

if _rs1_ != 0
{
  va := _rs1_
}
else
{
  va := _MATCH_ALL_VA_
}

if _rs2_ != 0
{
  asid := _rs2_
}
else
{
  asid := _MATCH_ALL_ASID_
}

msg := encode_invalidate_tlb(va, asid)
broadcast_to_all_harts(msg)
--

Permission::
This instruction can be executed in all privilege levels higher than `U` mode.
Attempts to execute this instruction in `U` mode raise an illegal instruction exception.

Exceptions::
This instruction does not trigger any exceptions.

Included in::
[%header]
|===
|Extension

|XTheadSync (<<#xtheasync>>)
|===
