[#xtheadsync-insns-sync-i,reftext=Synchronization pipeline flush]
==== th.sync.i

Synopsis::
Clear the pipeline when this instruction retires.

Mnemonic::
th.sync.i

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 0x0 },
    { bits:  3, name: 0x0, attr: ['CMO'] },
    { bits:  5, name: 0x0 },
    { bits:  5, name: 0x1A, attr: ['SYNC.I'] },
    { bits:  7, name: 0x00 },
]}
....

Description::
This instruction doesn't have the meaning of RISC-V standard fence instruction. It only flushes the pipeline of current hart. A sequence of th.icache.iall and th.sync.i has the same function with the RISC-V standard fence.i instrcution. When this instruction retires, the hart's pipeline will be cleared.

Operation::
[source,sail]
--
out_of_order_barrier()
pipeline_flush()
--

Permission::
This instruction can be executed in all privilege levels.

Exceptions::
This instruction does not trigger any exceptions.

Included in::
[%header]
|===
|Extension

|XTheadSync (<<#xtheasync>>)
|===
