[#xtheadsync-insns-sync-is,reftext=Synchronization barrier and pipeline flush on all harts]
==== th.sync.is

Synopsis::
Ensures that all preceding instructions retire earlier than this instruction on other harts and clears the pipeline of current hart when this instruction retires.

Mnemonic::
th.sync.is

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 0x0 },
    { bits:  3, name: 0x0, attr: ['CMO'] },
    { bits:  5, name: 0x0 },
    { bits:  5, name: 0x1B, attr: ['SYNC.IS'] },
    { bits:  7, name: 0x00 },
]}
....

Description::
This instruction ensures that all preceding instructions retire earlier than this instruction on other harts. When this instruction retires the hart's pipeline will be cleared. The instruction is executing on all harts via broadcasting. It only ensures that previous ops will not be delayed on other harts.

Operation::
[source,sail]
--
msg := encode_out_of_order_preceding_barrier()
broadcast_to_all_harts(msg)
pipeline_flush()
--

Permission::
This instruction can be executed in all privilege levels.

Exceptions::
This instruction does not trigger any exceptions.

Included in::
[%header]
|===
|Extension

|XTheadSync (<<#xtheasync>>)
|===
