[#xtheadcondmov-insns-mveqz,reftext=Move if equal zero]
==== th.mveqz

Synopsis::
Move if equal zero.

Mnemonic::
th.mveqz _rd_, _rs1_, _rs2_

Encoding::
[wavedrom, , svg]
....
{reg:[
    { bits:  7, name: 0xb, attr: ['custom-0, 32 bit'] },
    { bits:  5, name: 'rd' },
    { bits:  3, name: 0x1, attr: ['Arithmetic'] },
    { bits:  5, name: 'rs1' },
    { bits:  5, name: 'rs2' },
    { bits:  2, name: 0x00 },
    { bits:  5, name: 0x08 },
]}
....

Description::
This instruction moves the content of register _rs1_ into _rd_ if the content of _rs2_ is 0x0. Otherwise, the value of _rd_ does not change.

Operation::
[source,sail]
--
// illegal instruction exceptions
if (mxstatus.theadisaee != 1)
{
  <raise illegal instruction exception>
}

// execute instruction
if (reg[rs2] == 0x0)
  reg[rd] := reg[rs1]
--

Permission::
This instruction is available in `M` mode, `S` mode, and `U` mode.

Exceptions::
This instruction does not trigger any exceptions.

Availability::
The instruction is only available if `mxstatus.theadisaee` is set to `1`.
Otherwise this instruction will trigger an illegal instruction exception.

Included in::
[%header]
|===
|Extension

|XTheadCondMov (<<#xtheadcondmov>>)
|===
